## Pair Programming NumPy II - 02/12/2022

**1** Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:

El valor de la primera fila y la segunda columna.

Los valores de la segunda fila y las dos primeras columnas.

Extraed las filas pares (incluyendo la 0) y todas las columnas.

Extraed los valores que sean mayores que 0.5.

Extraed los valores menores que 0.2 o mayores que 0.5

In [3]:
import numpy as np

In [20]:
array1 = np.random.rand(2,5,3)
array1

array([[[0.47979149, 0.07836667, 0.49087277],
        [0.90721825, 0.46798993, 0.37635895],
        [0.04885464, 0.75341042, 0.79214726],
        [0.32383914, 0.60618219, 0.71777825],
        [0.46957085, 0.40951567, 0.89767393]],

       [[0.63221893, 0.62379752, 0.36070879],
        [0.61338174, 0.81844339, 0.16321409],
        [0.13030226, 0.52976425, 0.37474364],
        [0.97092172, 0.68150507, 0.73762853],
        [0.06011625, 0.80572778, 0.57569055]]])

In [21]:
# El valor de la primera fila y la segunda columna.

array1[0,1,2]

0.3763589454593538

In [22]:
# Los valores de la segunda fila y las dos primeras columnas.

array1[0,2,:2]

array([0.04885464, 0.75341042])

In [23]:
# Extraed las filas pares (incluyendo la 0) y todas las columnas

array1[0,::2,:]

array([[0.47979149, 0.07836667, 0.49087277],
       [0.04885464, 0.75341042, 0.79214726],
       [0.46957085, 0.40951567, 0.89767393]])

In [24]:
# Extraed los valores que sean mayores que 0.5.

array1[(array1>0.5)]

array([0.90721825, 0.75341042, 0.79214726, 0.60618219, 0.71777825,
       0.89767393, 0.63221893, 0.62379752, 0.61338174, 0.81844339,
       0.52976425, 0.97092172, 0.68150507, 0.73762853, 0.80572778,
       0.57569055])

In [25]:
# Extraed los valores menores que 0.2 o mayores que 0.5

array1[(array1<0.2)|(array1>0.5)]

array([0.07836667, 0.90721825, 0.04885464, 0.75341042, 0.79214726,
       0.60618219, 0.71777825, 0.89767393, 0.63221893, 0.62379752,
       0.61338174, 0.81844339, 0.16321409, 0.13030226, 0.52976425,
       0.97092172, 0.68150507, 0.73762853, 0.06011625, 0.80572778,
       0.57569055])

**2** Cread dos array de tres dimensiones:

El primero de 2 matrices, 5 filas y 3 columnas.

El segundo de 3 matrices, 2 filas y 5 columnas

Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una función para esto.

Sumad los dos arrays. ¿Podéis? ¿Por qué?

Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos aprendido dos métodos:

.reshape()
.transpose()

Utiliza estas dos funciones para cambiar la forma de los array y hacer operaciones entre ellos.

In [ ]:
# El primero de 2 matrices, 5 filas y 3 columnas.

In [30]:
array2 = np.random.rand(2,5,3)
array2

array([[[0.92903828, 0.54920033, 0.03073088],
        [0.78236883, 0.6362629 , 0.60278227],
        [0.88658118, 0.95910101, 0.06569103],
        [0.17526402, 0.3427832 , 0.35405564],
        [0.84272505, 0.82466892, 0.64871215]],

       [[0.50692908, 0.26294194, 0.5688257 ],
        [0.8782637 , 0.46608385, 0.0731295 ],
        [0.34031978, 0.97650163, 0.28725828],
        [0.11079632, 0.77486062, 0.13814283],
        [0.04226722, 0.48528127, 0.42308211]]])

In [31]:
# El segundo de 3 matrices, 2 filas y 5 columnas
array3 = np.random.rand(3,2,5)
array3

array([[[0.7494636 , 0.97932067, 0.47925986, 0.74292059, 0.25822112],
        [0.68238529, 0.84080158, 0.62142955, 0.40818188, 0.98113482]],

       [[0.78056058, 0.08360383, 0.65101434, 0.43882347, 0.12107296],
        [0.79674062, 0.99355063, 0.43043133, 0.59897636, 0.06536484]],

       [[0.54811572, 0.07646286, 0.42141578, 0.62566273, 0.75564784],
        [0.90604451, 0.12688183, 0.58320266, 0.9825613 , 0.87372228]]])

In [32]:
# Haced un análisis exploratorio de los array creados. 
# Recordad que en el ejercicio de ayer nos creamos una función para esto.

In [33]:
listaar = [array2, array3]

In [80]:
def exploracion_propiedades_array(lista_array):

    for i in lista_array:

        print( f"""Shape: {i.shape}
                Número de dimensiones: {i.ndim}
                Size: {i.size}
                Tipo: {i.dtype}""" )

In [81]:
exploracion_propiedades_array(listaar)

Shape: (2, 5, 3)
                Número de dimensiones: 3
                Size: 30
                Tipo: float64
Shape: (3, 2, 5)
                Número de dimensiones: 3
                Size: 30
                Tipo: float64


In [43]:
# Sumad los dos arrays. ¿Podéis? ¿Por qué?

# No se puede sumar porque tienen diferente shape. Se procede a cambiar la forma.

array2+array3

ValueError: operands could not be broadcast together with shapes (2,5,3) (3,2,5) 

In [45]:
# Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas 
# formas hemos aprendido dos métodos:
#.reshape()

array4 = array2.copy()
array4

array([[[0.92903828, 0.54920033, 0.03073088],
        [0.78236883, 0.6362629 , 0.60278227],
        [0.88658118, 0.95910101, 0.06569103],
        [0.17526402, 0.3427832 , 0.35405564],
        [0.84272505, 0.82466892, 0.64871215]],

       [[0.50692908, 0.26294194, 0.5688257 ],
        [0.8782637 , 0.46608385, 0.0731295 ],
        [0.34031978, 0.97650163, 0.28725828],
        [0.11079632, 0.77486062, 0.13814283],
        [0.04226722, 0.48528127, 0.42308211]]])

In [53]:
array2

array([[[0.92903828, 0.54920033, 0.03073088],
        [0.78236883, 0.6362629 , 0.60278227],
        [0.88658118, 0.95910101, 0.06569103],
        [0.17526402, 0.3427832 , 0.35405564],
        [0.84272505, 0.82466892, 0.64871215]],

       [[0.50692908, 0.26294194, 0.5688257 ],
        [0.8782637 , 0.46608385, 0.0731295 ],
        [0.34031978, 0.97650163, 0.28725828],
        [0.11079632, 0.77486062, 0.13814283],
        [0.04226722, 0.48528127, 0.42308211]]])

In [51]:
array4 = array4.reshape(3,2,5)
array4

array([[[0.92903828, 0.54920033, 0.03073088, 0.78236883, 0.6362629 ],
        [0.60278227, 0.88658118, 0.95910101, 0.06569103, 0.17526402]],

       [[0.3427832 , 0.35405564, 0.84272505, 0.82466892, 0.64871215],
        [0.50692908, 0.26294194, 0.5688257 , 0.8782637 , 0.46608385]],

       [[0.0731295 , 0.34031978, 0.97650163, 0.28725828, 0.11079632],
        [0.77486062, 0.13814283, 0.04226722, 0.48528127, 0.42308211]]])

In [55]:
# array4 + array3
np.add(array4,array3)

array([[[1.67850189, 1.52852099, 0.50999073, 1.52528942, 0.89448403],
        [1.28516756, 1.72738276, 1.58053056, 0.47387292, 1.15639883]],

       [[1.12334378, 0.43765947, 1.49373939, 1.26349239, 0.76978511],
        [1.3036697 , 1.25649257, 0.99925703, 1.47724006, 0.53144869]],

       [[0.62124522, 0.41678264, 1.39791741, 0.912921  , 0.86644416],
        [1.68090514, 0.26502467, 0.62546987, 1.46784257, 1.29680439]]])

In [72]:
array2

array([[[0.92903828, 0.54920033, 0.03073088],
        [0.78236883, 0.6362629 , 0.60278227],
        [0.88658118, 0.95910101, 0.06569103],
        [0.17526402, 0.3427832 , 0.35405564],
        [0.84272505, 0.82466892, 0.64871215]],

       [[0.50692908, 0.26294194, 0.5688257 ],
        [0.8782637 , 0.46608385, 0.0731295 ],
        [0.34031978, 0.97650163, 0.28725828],
        [0.11079632, 0.77486062, 0.13814283],
        [0.04226722, 0.48528127, 0.42308211]]])

In [60]:
array2.shape

(2, 5, 3)

In [61]:
array3.shape

(3, 2, 5)

In [73]:
#.transpose()

array5 = np.transpose(array2,(2,0,1))
array5

array([[[0.92903828, 0.78236883, 0.88658118, 0.17526402, 0.84272505],
        [0.50692908, 0.8782637 , 0.34031978, 0.11079632, 0.04226722]],

       [[0.54920033, 0.6362629 , 0.95910101, 0.3427832 , 0.82466892],
        [0.26294194, 0.46608385, 0.97650163, 0.77486062, 0.48528127]],

       [[0.03073088, 0.60278227, 0.06569103, 0.35405564, 0.64871215],
        [0.5688257 , 0.0731295 , 0.28725828, 0.13814283, 0.42308211]]])

In [56]:
# array5+array3
np.add(array5,array3)

array([[[1.67850189, 1.52852099, 0.50999073, 1.52528942, 0.89448403],
        [1.28516756, 1.72738276, 1.58053056, 0.47387292, 1.15639883]],

       [[1.12334378, 0.43765947, 1.49373939, 1.26349239, 0.76978511],
        [1.3036697 , 1.25649257, 0.99925703, 1.47724006, 0.53144869]],

       [[0.62124522, 0.41678264, 1.39791741, 0.912921  , 0.86644416],
        [1.68090514, 0.26502467, 0.62546987, 1.46784257, 1.29680439]]])