## Pair Programming NumPy I - 01/12/2022

1. Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota

El array de 2 dimensiones debe ser de 2 filas y 3 columnas

El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
import numpy as np

array unidimensional

In [3]:
# Creación con lista
lista1 = [2,4,6,8,10]

In [4]:
array1 = np.array(lista1)
array1

array([ 2,  4,  6,  8, 10])

In [5]:
# Creación con random. Estamos generando un array unidimensional con números aleatorios del 0-5. Con 5 filas
a1 = np.random.randint(0,5, (5,))

In [6]:
a1

array([0, 0, 3, 0, 2])

array bidimensional. Debe ser de 2 filas y 3 columnas

In [7]:
# Creación con listas
lista2 = [10,20,30]
lista3 = [40,50,60]

In [8]:
array2 = np.array([lista2, lista3]) 
array2

array([[10, 20, 30],
       [40, 50, 60]])

In [9]:
# Creación con random. Estamos generando un array con 1 matriz, de 2 filas y 3 columnas con números aleatorios del 0-60
a2 = np.random.randint(0,60, (1,2,3))

In [10]:
a2

array([[[ 8, 10, 41],
        [34, 57, 29]]])

array multidimensional. El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [11]:
# No es posible crearlo con listas, debe crearse con random, sino nos crea un array de 2 dimensiones con listas.
array3 = np.random.randint(0,100, (2,3,5))
array3

array([[[13, 52, 75, 94, 73],
        [72, 48,  0, 24, 37],
        [45, 56, 59, 49, 96]],

       [[29, 50, 29, 10, 93],
        [53, 83, 89, 37, 41],
        [25, 79, 36, 34, 84]]])

In [12]:
# Forma:
array3.shape

(2, 3, 5)

In [13]:
# Dimensiones
array3.ndim

3

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [32]:
def exploracion_propiedades_array(lista_array):

    for i in lista_array:

        print( f"""Shape: {i.shape}
                Número de dimensiones: {i.ndim}
                Size: {i.size}
                Tipo: {i.dtype}""" )

In [33]:
listaar = [array1,array2,array3]

In [34]:
exploracion_propiedades_array(listaar)

Shape: (5,)
                Número de dimensiones: 1
                Size: 5
                Tipo: int64
Shape: (2, 3)
                Número de dimensiones: 2
                Size: 6
                Tipo: int64
Shape: (2, 3, 5)
                Número de dimensiones: 3
                Size: 30
                Tipo: int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [28]:
array4 = np.identity(3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
array4.ndim

2

In [30]:
array4.shape

(3, 3)

**4.** Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

**5** Es el momento de hacer algunas operaciones entre arrays

5.1 ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

No, porque no tienen la misma forma. Los dos array tienen dos dimensiones, pero el array2 tiene dos filas y tres columnas y el array4 tiene tres filas y tres columnas.

In [31]:
np.add(array2,array4)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [ ]:
array2

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
array2.shape

(2, 3)

In [ ]:
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
array4.shape

(3, 3)

5.2 En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [ ]:
# Creamos un nuevo array con la misma forma que la primera matriz de identidad para poder sumarlas.
array5 = np.identity(3)
array5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Sumamos con su método propio
np.add(array4, array5)

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [ ]:
# Sumamos con operador +

5.3 Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [ ]:
# Multiplicamos con su método propio
np.multiply(array4, array5)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Miltiplicamos con operador *
print (array4 * array5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


5.4 Dividid las dos matricess

In [ ]:
# usando el método propio de NumPy

np.divide(array4, array5)

/tmp/ipykernel_488/3062029506.py:3: RuntimeWarning: invalid value encountered in true_divide
  np.divide(array4, array5)


array([[ 1., nan, nan],
       [nan,  1., nan],
       [nan, nan,  1.]])

In [ ]:
# usando el operador

print(array4 / array5)

[[ 1. nan nan]
 [nan  1. nan]
 [nan nan  1.]]


/tmp/ipykernel_488/1672076901.py:3: RuntimeWarning: invalid value encountered in true_divide
  print(array4 / array5)
