# Pair Programming NumPy IV

In [1]:
import numpy as np

1. ¿Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [23]:
np.random.seed(1)
arr1 = np.random.sample((4,4))
arr1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01]])

In [24]:
np.random.seed(1)
arr2 = np.random.sample((4,4))
arr2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01]])

2. Cread los siguientes arrays:
- Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.

In [12]:
array3 = np.random.randint(0,10, (2,3,5))
array3


array([[[7, 7, 9, 1, 7],
        [0, 6, 9, 9, 7],
        [6, 9, 1, 0, 1]],

       [[8, 8, 3, 9, 8],
        [7, 3, 6, 5, 1],
        [9, 3, 4, 8, 1]]])

In [14]:
uni_array3 = np.unique(array3)
uni_array3

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

- Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [16]:
array4= np.random.binomial(10, 0.3, size = (2,3,5))
array4

array([[[1, 1, 4, 1, 5],
        [3, 3, 5, 2, 3],
        [4, 2, 3, 3, 1]],

       [[4, 3, 2, 4, 2],
        [4, 5, 0, 3, 1],
        [4, 1, 2, 5, 2]]])

3. En esta lección hemos aprendido algunos métodos de teórias de conjuntos. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:

- Elementos comunes entre los dos arrays
- Unión de los dos arrays
- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos

⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [19]:
# Nos arroja los valores que están presentes en el array 3 y array 4, es decir, aquellos valores que comparten ambos.
np.intersect1d(array3,array4)

array([0, 1, 3, 4, 5])

In [20]:
# Este método une los valores únicos de los array 3 y 4.
np.union1d(array3,array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Este método muestra los valores únicos que están en el array 3, pero no en el array 4.
np.setdiff1d(array3, array4)

array([6, 7, 8, 9])

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.

In [25]:
array1 =  np.random.randint(0,80, (2,4,3))
array1

array([[[13,  9,  7],
        [63, 61, 22],
        [57,  1,  0],
        [60,  8, 13]],

       [[47, 72, 30],
        [71,  3, 70],
        [21, 49, 57],
        [ 3, 68, 24]]])

In [26]:
array2 =  np.random.randint(0,80, (2,4,3))
array2

array([[[43, 76, 26],
        [52, 41, 15],
        [64, 68, 25],
        [ 7, 26, 25]],

       [[22,  9, 67],
        [23, 27, 37],
        [57, 38,  8],
        [32, 34, 10]]])

Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.

In [28]:
array1 = np.unique(array1)
array1

array([ 0,  1,  3,  7,  8,  9, 13, 21, 22, 24, 30, 47, 49, 57, 60, 61, 63,
       68, 70, 71, 72])

In [29]:
array2 = np.unique(array2)
array2

array([ 7,  8,  9, 10, 15, 22, 23, 25, 26, 27, 32, 34, 37, 38, 41, 43, 52,
       57, 64, 67, 68, 76])

Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [30]:
aray3 = np.setdiff1d(array1, array2)
aray3

array([ 0,  1,  3, 13, 21, 24, 30, 47, 49, 60, 61, 63, 70, 71, 72])

Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [31]:
aray4 = np.setdiff1d(array2, array1)
aray4

array([10, 15, 23, 25, 26, 27, 32, 34, 37, 38, 41, 43, 52, 64, 67, 76])

Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [32]:
array5 = np.intersect1d(array1, array2)
array5

array([ 7,  8,  9, 22, 57, 68])

¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [42]:
suma1 = array1.size + aray4.size
suma1

37

In [43]:
suma2 = array2.size + aray3.size
suma2

37

In [44]:
# La suma de la longitud del array1 y del array4 es igual a la suma de la longitud del array2 y array3.
suma1==suma2

True

In [45]:
resta1= suma1-array5.size
resta1

31

In [46]:
resta2= suma2-array5.size
resta2

31

In [47]:
# La suma de la longitud del array1 y del array4 menos el array5 es igual a la suma de la longitud del array2 y array3 menos el array5.
resta1==resta2

True

In [48]:
# La longitud del array2 es igual a la suma de la longitud del array4 y array5
aray4.size + array5.size == array2.size

True

In [35]:
array1.size

21

In [36]:
array2.size

22

In [37]:
aray3.size


15

In [38]:
aray4.size


16

In [39]:
array5.size

6