Pair Programming NumPy III

En esta lección hemps aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.


1. Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [1]:
import numpy as np 


In [4]:
array1 = np.round(np.random.rand(2,3,5),decimals = 1)
array1

array([[[0.1, 0.4, 1. , 0.1, 0.3],
        [0.5, 0.7, 0.3, 0.3, 0.6],
        [0.3, 0.9, 0. , 0.1, 1. ]],

       [[0.5, 0.3, 0.4, 0.6, 0. ],
        [0.3, 0.1, 0.9, 0.9, 0.4],
        [1. , 0.5, 0.6, 0. , 0.1]]])

Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
media = np.round(np.mean(array1), decimals = 1)
media

0.4

Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [6]:
maximo = np.round(np.max(array1), decimals = 1)
maximo

1.0

Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [7]:
minimo = np.round(np.min(array1), decimals = 1)
minimo

0.0

Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [58]:
array2 = np.empty((2,3,5), dtype = str)
array2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [13]:
media2 = np.round(np.mean(array1), decimals = 1)
media2

0.4

In [42]:
for n in array1:
    for i in n:
        for f in i:
            #print(f)
            if f == media:
                if np.where(array2 == media):
                    indice.replace('A') 
                    print(array2)
                #for i in array2:
                    #for n in i:
                        #print(n)
                        #for m in n:
                            #m == 'A'

                            

                

for x in a[:]:
    x[0]=b[a.index(x)]

[['bar', 2, 3], ['foo', 3, 4], ['car', 4, 5]]    


AttributeError: 'tuple' object has no attribute 'replace'

In [49]:
for i in np.where(array2 == media):
    print(i)
    

   

[0 1 1]
[0 0 1]
[1 2 4]


In [61]:
if np.where(array1 == media):
    array2[np.where(array1 == media)] = 'A'
    print(array2)

[[['' 'A' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' 'A' '' '']
  ['' '' '' '' 'A']
  ['' '' '' '' '']]]
