### Pair Programming NumPy III

En esta lección hemps aprendido algunas de las operaciones matemáticas más importantes que podemos aplicar a un array. Hoy pondremos en práctica algunas de estas operaciones, además de recordar algunas de los métodos aprendidos en otras lecciones y recordar como podemos iterar por un array.


**1.** Cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:

In [1]:
import numpy as np 


In [2]:
array1 = np.round(np.random.rand(2,3,5),decimals = 1)
array1

array([[[0.5, 0.6, 0.9, 0.8, 0.2],
        [0.4, 0.7, 0.1, 0.5, 0.4],
        [0.1, 0.1, 0.3, 0.6, 0. ]],

       [[0. , 0.4, 0.2, 0.2, 0.6],
        [0.5, 0.7, 0.7, 0.7, 0.8],
        [0.5, 0.5, 0.7, 0. , 0.1]]])

**2.** Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.

In [3]:
media = np.round(np.mean(array1), decimals = 1)
media

0.4

**3.** Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.

In [4]:
maximo = np.round(np.max(array1), decimals = 1)
maximo

0.9

**4.** Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [5]:
minimo = np.round(np.min(array1), decimals = 1)
minimo

0.0

**5.** Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [52]:
# Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
array2 = np.empty((2,3,5), dtype = str)
array2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [20]:
# for i in np.where(array1 == media):
    # print(i)
      

[0 0 1]
[1 1 0]
[0 4 1]


**5.1** Condiciones

In [53]:
array2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [54]:
# - Si el valor del array es igual que la media, se reemplaza por "A".
if np.where(array1 == media):
    array2[np.where(array1 == media)] = 'A'
# - Si el valor del array es mayor que la media, se reemplaza por "B".
    if np.where(array1 > media):
        array2[np.where(array1 > media)] = 'B'
# - Si el valor del array es menor que la media, se reemplaza por "C".
        if np.where(array1 < media):
            array2[np.where(array1 < media)] = 'C'
# - Si el valor es igual que el máximo, se reemplaza por "D".
            if np.where(array1 == maximo):
                array2[np.where(array1 == maximo)] = 'D'
# - Si el valor es igual que el mínimo, se reemplaza por "E".
                if np.where(array1 == minimo):
                    array2[np.where(array1 == minimo)] = 'E'

print (array2)

[[['B' 'B' 'D' 'B' 'C']
  ['A' 'B' 'C' 'B' 'A']
  ['C' 'C' 'C' 'B' 'E']]

 [['E' 'A' 'C' 'C' 'B']
  ['B' 'B' 'B' 'B' 'B']
  ['B' 'B' 'B' 'E' 'C']]]


**6** Estupendo, tenemos un array con strings. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.

En este caso:
- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
- Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [56]:
array3 = np.empty((30,), dtype = int)
array3

array([4602678819172646912, 4603579539098121011, 4606281698874543309,
       4605380978949069210, 4596373779694328218, 4600877379321698714,
       4604480259023595110, 4591870180066957722, 4602678819172646912,
       4600877379321698714, 4591870180066957722, 4591870180066957722,
       4599075939470750515, 4603579539098121011,                   0,
                         0, 4600877379321698714, 4596373779694328218,
       4596373779694328218, 4603579539098121011, 4602678819172646912,
       4604480259023595110, 4604480259023595110, 4604480259023595110,
       4605380978949069210, 4602678819172646912, 4602678819172646912,
       4604480259023595110,                   0, 4591870180066957722])

In [60]:
# - Si el valor del array es igual que la media, se reemplaza por "A".
#if np.where(array2 == "A" or "B"):
    #array3[np.where(array2 == "A" or "B")] = 1
# - Si el valor del array es mayor que la media, se reemplaza por "B".
    #if np.where(array2 == "C" or "D"):
        #array3[np.where(array2 == "C" or "D")] = 2
if np.where(array2 == "E"):
    array3[np.where(array2 == "E" )] = 3

print (array3)

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [68]:
for n in array2:
    if n == "E":
        n == 3

print (array3)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()