## Pair Programming NumPy I - 01/12/2022

1. Cread tres arrays: de una, dos y tres dimensiones.

Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.

📌 Nota

El array de 2 dimensiones debe ser de 2 filas y 3 columnas

El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [1]:
import numpy as np

array unidimensional

In [106]:
# Creación con lista
lista1 = [2,4,6,8,10]

In [105]:
array1 = np.array(lista1)
array1

array([ 2,  4,  6,  8, 10])

In [102]:
# Creación con random. Estamos generando un array unidimensional con números aleatorios del 0-5. Con 5 filas
a1 = np.random.randint(0,5, (5,))

In [103]:
a1

array([1, 2, 2, 4, 4])

array bidimensional. Debe ser de 2 filas y 3 columnas

In [107]:
# Creación con listas
lista2 = [10,20,30]
lista3 = [40,50,60]

In [108]:
array2 = np.array([lista2, lista3]) 
array2

array([[10, 20, 30],
       [40, 50, 60]])

In [113]:
# Creación con random. Estamos generando un array con 1 matriz, de 2 filas y 3 columnas con números aleatorios del 0-60
a2 = np.random.randint(0,60, (1,2,3))

In [114]:
a2

array([[[18,  1, 58],
        [ 1, 47, 58]]])

array multidimensional. El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [115]:
# No es posible crearlo con listas, debe crearse con random, sino nos crea un array de 2 dimensiones con listas.
array3 = np.random.randint(0,100, (2,3,5))
array3

array([[[22, 68, 78,  1, 95],
        [66, 54, 17, 67, 21],
        [45, 13,  2, 52, 59]],

       [[44, 65, 36, 70, 30],
        [ 0, 11, 92, 98,  5],
        [ 0, 67, 19, 47, 29]]])

In [116]:
# Forma:
array3.shape

(2, 3, 5)

In [117]:
# Dimensiones
array3.ndim

3

2. Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

Propiedades array 1. Unidimensional

In [24]:
# Forma
array1.shape 

(5,)

In [25]:
# Size
array1.size

5

In [27]:
# Número de dimensiones
array1.ndim

1

In [118]:
# Tipo
array1.dtype

dtype('int64')

Propiedades array 2. Bidimensional

In [54]:
# Forma
array2.shape 

(2, 3)

In [30]:
# Size
array2.size

6

In [119]:
# Número de dimensiones
array2.ndim

2

In [120]:
# Tipo
array2.dtype

dtype('int64')

Propiedades array 3. Multidimensional

In [121]:
# Forma
array3.shape 

(2, 3, 5)

In [122]:
# Size
array3.size

30

In [123]:
# Número de dimensiones
array3.ndim

3

In [124]:
# Tipo
array3.dtype

dtype('int64')

3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [125]:
array4 = np.identity(3)
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [126]:
array4.ndim

2

In [127]:
array4.shape

(3, 3)

**4.** Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

**5** Es el momento de hacer algunas operaciones entre arrays

5.1 ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?

No, porque no tienen la misma forma. Los dos array tienen dos dimensiones, pero el array2 tiene dos filas y tres columnas y el array4 tiene tres filas y tres columnas.

In [39]:
np.add(array2,array4)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [43]:
array2

array([[10, 20, 30],
       [40, 50, 60]])

In [41]:
array2.shape

(2, 3)

In [44]:
array4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
array4.shape

(3, 3)

5.2 En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.

In [45]:
# Creamos un nuevo array con la misma forma que la primera matriz de identidad para poder sumarlas.
array5 = np.identity(3)
array5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
# Sumamos con su método propio
np.add(array4, array5)

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [48]:
# Sumamos con operador +

5.3 Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.

In [51]:
# Multiplicamos con su método propio
np.multiply(array4, array5)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
# Miltiplicamos con operador *
print (array4 * array5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


5.4 Dividid las dos matricess

In [53]:
# usando el método propio de NumPy

np.divide(array4, array5)

/tmp/ipykernel_488/3062029506.py:3: RuntimeWarning: invalid value encountered in true_divide
  np.divide(array4, array5)


array([[ 1., nan, nan],
       [nan,  1., nan],
       [nan, nan,  1.]])

In [52]:
# usando el operador

print(array4 / array5)

[[ 1. nan nan]
 [nan  1. nan]
 [nan nan  1.]]


/tmp/ipykernel_488/1672076901.py:3: RuntimeWarning: invalid value encountered in true_divide
  print(array4 / array5)
