## Pair Programming Panda I - 01/12/2022

El objetivo de la clase de hoy será crear unos cuántos DataFrames y Series a través de los siguientes ejercicios:

**1** ¿Qué diferencia hay entre una Serie y un DataFrame?

Una serie tiene una estructura unidimensional y el DataFrame es bidimensional

**2.** Momento de trabajar con Series. Contestad a las siguientes preguntas:

2.1 Crea dos listas:

Una que se llame "valores" que tenga 7 números aleatorios.

Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

In [79]:
valores = [12,6,20,8,17,7,9]
indices = ["lunes", "martes", "miércoles", "jueves", "viernes" , "sabado" , "domingo"]

2.2 A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

In [80]:
diccionario1 = {}

In [81]:
for n,p in zip(indices,valores):
    diccionario1.setdefault(n,p)

In [82]:
diccionario1

{'lunes': 12,
 'martes': 6,
 'miércoles': 20,
 'jueves': 8,
 'viernes': 17,
 'sabado': 7,
 'domingo': 9}

2.3 Crea una Serie con el diccionario creado en el punto anterior.

In [83]:
import pandas as pd
import numpy as np

In [84]:
serie1= pd.Series(diccionario1)
serie1

lunes        12
martes        6
miércoles    20
jueves        8
viernes      17
sabado        7
domingo       9
dtype: int64

2.4 ¿Qué forma tiene esta última Serie?

In [85]:
serie1.shape

(7,)

2.5 ¿Qué tipo de datos tiene?

In [86]:
serie1.dtypes

dtype('int64')

2.6 ¿Qué tamaño tiene?

In [87]:
serie1.size

7

2.7 ¿Cuáles son los índices de la Serie?

In [88]:
serie1.index

Index(['lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

2.8 ¿Y los values?

In [89]:
serie1.values

array([12,  6, 20,  8, 17,  7,  9])

2.9 Extraed el valor para el índice "lunes"

In [90]:
## Si quiero acceder al elemento que esta en la posición 2 

serie1["lunes"]

12

2.10 Extraed el valor para el índice "lunes", "martes" y "miércoles".

In [91]:
serie1["lunes":"miércoles"]

lunes        12
martes        6
miércoles    20
dtype: int64

2.11 Extraed el valor para el índice "lunes" y "domingo".

In [129]:
serie1[["lunes","domingo"]].values

array([12,  9])

**3.** Es el turno de los DataFrames

3.1 Cread un array de dos dimensiones con 4 filas y 3 columnas.

In [92]:
array2 = np.random.randint(0,20, (4,3))
array2

array([[ 8,  3,  5],
       [ 5, 10, 16],
       [16, 10,  2],
       [16, 14,  9]])

3.2 Convertid el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [93]:
paises = pd.DataFrame(array2, columns = ["España", "Francia", "Italia"])
paises

España  Francia  Italia
0       8        3       5
1       5       10      16
2      16       10       2
3      16       14       9

3.3 Descargad el archivo "medallas" y cargad el DataFrame con la siguiente línea de código:

In [94]:
df = pd.read_csv("medallas.csv", index_col=["País"])

In [95]:
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

3.3.1 Usando el loc extraed todas las columnas de la fila.

In [96]:
df.loc[:, :]

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

3.3.2 Usando el loc extraed todas las columnas de China e Irán.

In [97]:
df.loc[("China","Irán"), :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

3.3.3 Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.

In [98]:
df.loc[("China","Irán"), ("Oro","Plata","Bronce")]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

3.3.4 Usando el iloc extraed la información de la India. Devolved todas las columnas.

In [99]:
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [100]:
df.iloc[5,:]

Unnamed: 0      6
Oro           154
Plata         202
Bronce        315
Name: India, dtype: int64

3.3.5 Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [101]:
df.iloc[1::2, :]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

3.3.6 Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

In [102]:
df.iloc[1::2,[1,2,3]]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

3.3.7 Contestad a las siguientes preguntas:

In [103]:
# ¿Qué país consiguió más de 200 medallas de oro?
df.loc[df.Oro > 200, :]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [104]:
# ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

df.loc[(df.Oro > 200) & (df.Plata > 1000)]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

In [105]:
# ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

df.loc[(df.Oro > 200) | (df.Plata > 700)]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

3.3.8 Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.

In [106]:
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [107]:
df3 = df.drop( 
    df.iloc[:,0:1].columns,
    axis=1)

In [108]:
df3

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

3.3.9 Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [109]:
df3["total"] = (df["Oro"]+df["Plata"]+df["Bronce"])

In [110]:
df3

Oro  Plata  Bronce  total
País                                       
China            1473    994     720   3187
Japón            1032   1037     985   3054
Corea del Sur     745    663     827   2235
Irán              179    181     197    557
Kazajistán        155    158     224    537
India             154    202     315    671
Tailandia         132    175     278    585
Indonesia         112    131     240    483
China Taipéi       99    144     276    519
Corea del Norte    91    120     235    446